clusters:
- cluster:
    certificate-authority: ./kube/ca.crt
    server: https://192.168.49.2:8443
users:
- name: minikube
  user:
    client-certificate: ./kube/client.crt
    client-key: ./kube/client.key
